export { default as StartScreen } from './StartScreen'
export { default as EndScreen } from './EndScreen'
// export { default as Game } from './Game'
export { default as Display } from './Display'
export { default as Question } from './Question'
export { default as PotentialAnswer } from './PotentialAnswer'
export { default as Count } from './Count'
export { default as Results } from './Results'
export { default as Button } from './Button'
